# General setup
# -------------
language: python
python:
    - "2.7"
# Allows the python virtualenv to use apt-get installed packages, which
# is essential (as ROS recommends this and pip doesn't seem to contain
# all packages, or contains them with errors).
virtualenv:
    system_site_packages: true
# Allow caching of debian (apt-get) packages. This means they're cached
# on Travis, so we still have to download/install them, but it will be
# faster than going to the ubuntu repositories.
cache: apt
# Before anything, see if we can get the mongoDB troubles out of the way.
# Note that this is a Travis-CI specific problem; this is not needed in
# general.
before_install:
    - sudo apt-get --purge remove mongodb-10gen postgresql-9.2 postgresql-contrib-9.2 postgresql-9.3 postgresql-contrib-9.3
    - export ROS_DISTRO=hydro
    # Settings to make installing script more general.
    - export ROS_CI_DESKTOP=`lsb_release -cs`  # e.g. 'precise'
    - export ROS_MASTER_URI=http://localhost:11311

notifications:
    email: false

# Commands to install dependencies
# --------------------------------
install:
    # Install ROS
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
    - sudo pip install -U setuptools
    - sudo pip install -U catkin_tools
    - source /opt/ros/$ROS_DISTRO/setup.bash
    # Setup rosdep
    - sudo rosdep init
    - rosdep update
    # Create workspace.
    - mkdir -p ~/catkin_ws/src
    - mv ../pr2_pbd ~/catkin_ws/src
    - cd ~/catkin_ws/src
    - git clone https://github.com/jstnhuang/mongo_msg_db_msgs.git
    - git clone https://github.com/jstnhuang/mongo_msg_db.git
    - git clone https://github.com/jstnhuang/agile_grasp.git
    - git clone https://github.com/hcrlab/blinky.git
    - git clone https://github.com/jstnhuang/rapid.git
    - cd ~/catkin_ws
    - catkin init
    # Install dependencies
    - rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y

# Command to run tests
# --------------------
script:
    # Build
    - catkin build pbd_landmarks
    - catkin build pr2_arm_control
    - catkin build pr2_pbd_gui
    - catkin build pr2_pbd_interaction
    - catkin build pr2_pbd_speech_recognition
    - catkin build pr2_social_gaze
    - catkin build tabletop_object_detector
# Real tests: crash because of Gazebo bugs
#    - roslaunch pr2_pbd_interaction simulated_robot.launch gui:=false
# Debug: trying to just run gazebo's table object launch (Gazebo bugs)
#    - rostest pr2_pbd_interaction test_endtoend.test
# Linter: last resort to getting *something* useful to run on Travis :-)
# NOTE(mbforbes): Add more files to this as they're completed.
#    - pep8 src/*.py test/*.py nodes/*.py
